---
- name: Debug
  ansible.builtin.debug:
    var: hostvars["reportsrvr1"]

- name: Install apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Change apache to specified port
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{ web_port }}'

# - name: Set nis_enabled flag on and keep it persistent across reboots
#   become: true
#   ansible.posix.seboolean:
#     name: nis_enabled
#     state: true
#     persistent: true

- name: Start httpd
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Create HTML report
  become: true
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/index.html"

- name: Copy CSS over
  become: true
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: Copy CSS over
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ file_path }}"
    directory_mode: true
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "gcp.png"

- name: Print variables
  ansible.builtin.debug:
    var: hostvars['reportsrvr1']

- name: Retrieve public IP address
  ansible.builtin.command: curl https://ifconfig.me
  register: public_ip_report
  ignore_errors: true

- name: Display link to inventory report
  ansible.builtin.debug:
    msg:
      - "Please go to http://{{ public_ip_report.stdout | default(ansible_fqdn) }}:{{ web_port }}"
