---
- name: Get list of all Zones
  ansible.builtin.shell: |
    gcloud compute zones list --uri \
      --account=${GCE_EMAIL} \
      --project=${GCP_PROJECT} \
      --credential-file-override=${GCE_CREDENTIALS_FILE_PATH} \
      | sed -e 's,.*/,,'
  register: all_zones
  changed_when: false
  environment:
    GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
    GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

- name: Print var all_zones
  ansible.builtin.debug:
    msg: "{{ all_zones.stdout_lines }}"

- name: Get all virtual networks
  google.cloud.gcp_compute_network_info:
    auth_kind: serviceaccount
  register: gcp_networks

- name: Print Virtual Network Information
  ansible.builtin.debug:
    msg:
      - "Network Name:                  {{ item.name }}"
      - "Network ID:                    {{ item.id }}"
      - "Auto Create Subnetworks:       {{ item.autoCreateSubnetworks }}"
  loop: "{{ gcp_networks.resources | list }}"
  loop_control:
    label: "Virtual Network Information"

- name: Retrieve VMs from your environment
  google.cloud.gcp_compute_instance_info:
    zone: "{{ item }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
  loop: "{{ all_zones.stdout_lines }}"
  register: gcp_vms

- name: Print the Number of VMs
  ansible.builtin.debug:
    msg: "{{ gcp_vms }}"
