---
- name: Get list of all Zones
  ansible.builtin.shell: |
    gcloud compute zones list --uri \
      --account=${GCE_EMAIL} \
      --project=${GCP_PROJECT} \
      --credential-file-override=${GCE_CREDENTIALS_FILE_PATH} \
      | sed -e 's,.*/,,'
  register: all_zones
  changed_when: false
  environment:
    GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
    GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

- name: Print var all_zones
  ansible.builtin.debug:
    msg: "{{ all_zones.stdout_lines }}"

- name: Get all virtual networks
  google.cloud.gcp_compute_network_info:
    auth_kind: serviceaccount
  register: gcp_networks

- name: Print Virtual Network Information
  ansible.builtin.debug:
    msg:
      - "Network Name:                  {{ item.name }}"
      - "Network ID:                    {{ item.id }}"
      - "Auto Create Subnetworks:       {{ item.autoCreateSubnetworks }}"
  loop: "{{ gcp_networks.resources | list }}"
  loop_control:
    label: "Virtual Network Information"

- name: Retrieve VMs from your environment
  google.cloud.gcp_compute_instance_info:
    zone: "{{ item }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
  register: gcp_vms
  loop: "{{ all_zones.stdout_lines }}"

- name: Print the Number of VMs
  ansible.builtin.debug:
    msg: "There are {{ gcp_vms }} virtual machine(s) that match your filter"

- name: Print the VM details
  ansible.builtin.debug:
    msg:
      - "VM Instance Name:             {{ item.name | default('The tag *Name* Does not exist') }}"
      - "VM Instance ID:               {{ item.id }}"
      - "VM Labels:                    {{ item.labels | default('NO *Labels* exist') }}"
      - "VM Instance State:            {{ item.status }}"
  loop: "{{ gcp_vms.resources | list }}"
  loop_control:
    label: "virtual machine info and associated labels"

# - name: Get facts for network interfaces
#   ansible.builtin.shell: |
#     gcloud compute instances network-interfaces get-effective-firewalls \
#       --account=${GCE_EMAIL} \
#       --project=${GCP_PROJECT} \
#       --credential-file-override=${GCE_CREDENTIALS_FILE_PATH}
#   register: network_interfaces
#   changed_when: false
#   environment:
#     GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
#     GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
#     GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

# - name: Print network interfaces
#   ansible.builtin.debug:
#     msg: "{{ network_interfaces }}"
#
