---
- name: Retrieve Network Interface details
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Get network interfaces information
      ansible.builtin.shell: |
        gcloud compute instances network-interfaces get-effective-firewalls \
          --account=${GCE_EMAIL} \
          --project=${GCP_PROJECT} \
          --credential-file-override=${GCE_CREDENTIALS_FILE_PATH}
        register: network_interfaces
        changed_when: false
        environment:
        GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
        GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

    - name: Print network interfaces
      ansible.builtin.debug:
        msg: "{{ network_interfaces }}"
