---
- name: Retrieve hosts with your_tags filter
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve vms from your_location
      google.cloud.gcp_compute_instance_info:
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
      register: retrieved_info

    - name: Print retrieved_info
      ansible.builtin.debug:
        msg: "There are {{ retrieved_info.resources | length }} virtual machine(s) that match your filter"

    - name: Print Labels
      ansible.builtin.debug:
        msg:
          - "VM Instance Name:             {{ item.name | default('The tag *Name* Does not exist') }}"
          - "VM Instance ID:               {{ item.id }}"
          - "VM Labels:                    {{ item.labels | default('NO *Labels* exist') }}"
          - "VM Instance State:            {{ item.status }}"
      loop: "{{ retrieved_info.resources | list }}"
      loop_control:
        label: "virtual machine info and associated labels"

    - name: Save the instances to be used in a workflow variable for following job templates
      ansible.builtin.set_stats:
        data:
          vm_name_list: "{{ retrieved_info.resources | map(attribute='name') | list }}"
        per_host: false
      when: retrieved_info.resources | length > 0
