---
- name: Retrieve hosts with your_tags filter
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve vms from your_location
      google.cloud.gcp_compute_instance_info:
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
      register: retrieved_info

    - name: Print retrieved_info
      ansible.builtin.debug:
        msg: "{{ retrieved_info }}"
