---
- name: Retrieve regions
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get list of all regions
      ansible.builtin.shell: |
        gcloud compute regions list | grep ^NAME | sed -e 's/NAME: //' \
          --account=${GCE_EMAIL} \
          --project=${GCP_PROJECT} \
          --credential-file-override=${GCE_CREDENTIALS_FILE_PATH} \
          --format=json
      register: all_regions
      changed_when: false
      environment:
        GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
        GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

    - name: Print var all_regions
      ansible.builtin.debug:
        msg: "{{ all_regions.stdout_lines }}"
