---
- name: Retrieve zones
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get list of all Zones
      ansible.builtin.shell: |
        gcloud compute zones list --uri \
          --account=${GCE_EMAIL} \
          --project=${GCP_PROJECT} \
          --credential-file-override=${GCE_CREDENTIALS_FILE_PATH} \
          | sed -e 's,.*/,,'
      register: all_zones
      changed_when: false
      environment:
        GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
        GCP_PROJECT: "{{ lookup('env', 'GCP_PROJECT') }}"
        GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

    - name: Print var all_zones
      ansible.builtin.debug:
        msg: "{{ all_zones.stdout_lines }}"
